import asyncio
import aiohttp
from termcolor import colored
import time

MAX_CONCURRENT_REQUESTS = 100
TIMEOUT = 5

async def find_admin_login(url):
    start_time = time.time()
    common_admin_paths = get_common_admin_paths()
    found_count = 0
    total_paths = len(common_admin_paths)
    print(colored("Scanning for admin login paths...", 'cyan'))

    async with aiohttp.ClientSession() as session:
        tasks = []
        scanned_paths = []

        for path in common_admin_paths:
            task = asyncio.ensure_future(scan_admin_path(session, url, path, scanned_paths))
            tasks.append(task)

        responses = await asyncio.gather(*tasks)

        for response in responses:
            if response:
                found_count += 1
                print(colored(f"Admin login found: {url.rstrip('/') + response}", 'green'))

    end_time = time.time()
    duration = end_time - start_time
    print(colored(f"\nTotal admin paths found: {found_count}", 'yellow'))
    print(colored(f"Time taken: {duration:.2f} seconds", 'yellow'))

async def scan_admin_path(session, url, path, scanned_paths):
    admin_url = url.rstrip('/') + path
    scanned_paths.append(path)
    try:
        async with session.get(admin_url, timeout=TIMEOUT) as response:
            if response.status == 200:
                return path
    except aiohttp.ClientError as e:
        print(colored(f"Error scanning path {admin_url}: {e}", 'red'))
    except asyncio.TimeoutError:
        print(colored(f"Timeout scanning path {admin_url}", 'red'))

async def main():
    url = input("Enter the URL you want to scan: ").strip()
    if not url.startswith(('http://', 'https://')):
        url = 'http://' + url

    await find_admin_login(url)

def get_common_admin_paths():
    common_admin_paths = [
        '/admin', '/administrator', '/login', '/wp-admin', '/admin/login.php',
        '/admin/login', '/user/login', '/cpanel', '/admin.php', '/wp-login.php',
        '/wp-login', '/admin/', '/administrator/', '/login/', '/wp-admin/',
        '/admin.php/', '/admin/login.php/', '/admin/login/', '/user/login/',
        '/cpanel/', '/admin.asp', '/administrator.asp', '/login.asp',
        '/wp-admin.asp', '/admin/login.asp', '/admin/login.asp', '/user/login.asp',
        '/cpanel.asp', '/admin.php', '/administrator.php', '/login.php',
        '/wp-admin.php', '/admin/login.php', '/admin/login.php', '/user/login.php',
        '/cpanel.php', '/admin.jsp', '/administrator.jsp', '/login.jsp',
        '/wp-admin.jsp', '/admin/login.jsp', '/admin/login.jsp', '/user/login.jsp',
        '/cpanel.jsp', '/admin.html', '/administrator.html', '/login.html',
        '/wp-admin.html', '/admin/login.html', '/admin/login.html', '/user/login.html',
        '/cpanel.html', '/admin.js', '/administrator.js', '/login.js',
        '/wp-admin.js', '/admin/login.js', '/admin/login.js', '/user/login.js',
        '/cpanel.js', '/admin.cgi', '/administrator.cgi', '/login.cgi',
        '/wp-admin.cgi', '/admin/login.cgi', '/admin/login.cgi', '/user/login.cgi',
        '/cpanel.cgi', '/admin.pl', '/administrator.pl', '/login.pl',
        '/wp-admin.pl', '/admin/login.pl', '/admin/login.pl', '/user/login.pl',
        '/cpanel.pl', '/admin/config', '/administrator/config', '/login/config',
        '/wp-admin/config', '/admin/login/config', '/admin/login/config',
        '/user/login/config', '/cpanel/config', '/admin/administrators',
        '/administrator/administrators', '/login/administrators',
        '/wp-admin/administrators', '/admin/login/administrators',
        '/admin/login/administrators', '/user/login/administrators',
        '/cpanel/administrators', '/admin/admin', '/administrator/admin',
        '/login/admin', '/wp-admin/admin', '/admin/login/admin', '/admin/login/admin',
        '/user/login/admin', '/cpanel/admin', '/admin/administrator',
        '/administrator/administrator', '/login/administrator', '/wp-admin/administrator',
        '/admin/login/administrator', '/admin/login/administrator', '/user/login/administrator',
        '/cpanel/administrator', '/admin/administration', '/administrator/administration',
        '/login/administration', '/wp-admin/administration', '/admin/login/administration',
        '/admin/login/administration', '/user/login/administration', '/cpanel/administration',
        '/admin/auth', '/administrator/auth', '/login/auth', '/wp-admin/auth',
        '/admin/login/auth', '/admin/login/auth', '/user/login/auth', '/cpanel/auth',
        '/admin/admin_auth', '/administrator/admin_auth', '/login/admin_auth',
        '/wp-admin/admin_auth', '/admin/login/admin_auth', '/admin/login/admin_auth',
        '/user/login/admin_auth', '/cpanel/admin_auth', '/admin/administrator_auth',
        '/administrator/administrator_auth', '/login/administrator_auth',
        '/wp-admin/administrator_auth', '/admin/login/administrator_auth',
        '/admin/login/administrator_auth', '/user/login/administrator_auth',
        '/cpanel/administrator_auth', '/admin/authenticate', '/administrator/authenticate',
        '/login/authenticate', '/wp-admin/authenticate', '/admin/login/authenticate',
        '/admin/login/authenticate', '/user/login/authenticate', '/cpanel/authenticate',
        '/admin/admin_authenticate', '/administrator/admin_authenticate',
        '/login/admin_authenticate', '/wp-admin/admin_authenticate',
        '/admin/login/admin_authenticate', '/admin/login/admin_authenticate',
        '/user/login/admin_authenticate', '/cpanel/admin_authenticate',
        '/admin/administrator_authenticate', '/administrator/administrator_authenticate',
        '/login/administrator_authenticate', '/wp-admin/administrator_authenticate',
        '/admin/login/administrator_authenticate', '/admin/login/administrator_authenticate',
        '/admin/auth_login', '/administrator/auth_login', '/login/auth_login',
        '/wp-admin/auth_login', '/admin/login/auth_login', '/admin/login/auth_login',
        '/user/login/auth_login', '/cpanel/auth_login', '/admin/admin_auth_login',
        '/administrator/admin_auth_login', '/login/admin_auth_login',
        '/wp-admin/admin_auth_login', '/admin/login/admin_auth_login',
        '/admin/login/admin_auth_login', '/user/login/admin_auth_login',
        '/cpanel/admin_auth_login', '/admin/administrator_auth_login',
        '/administrator/administrator_auth_login', '/login/administrator_auth_login',
        '/wp-admin/administrator_auth_login', '/admin/login/administrator_auth_login',
        '/admin/login/administrator_auth_login', '/user/login/administrator_auth_login',
        '/cpanel/administrator_auth_login',
        # Uncommon and rare paths
        '/secret', '/hidden', '/secure', '/admin-portal', '/admin-console',
        '/admin-login', '/private', '/confidential', '/management', '/control',
        '/adm', '/restricted', '/backdoor', '/root', '/superuser', '/sadmin',
        '/supervisor', '/manager', '/admin1', '/admin2', '/admin3', '/admin4',
        '/admin5', '/admin6', '/admin7', '/admin8', '/admin9', '/admin10',
        '/admin11', '/admin12', '/admin13', '/admin14', '/admin15',
        '/super', '/login_admin', '/login_administrator', '/admin_panel',
        '/admin-area', '/admincp', '/controlpanel', '/userpanel', '/panel',
        '/user', '/useradmin', '/user-admin', '/clients', '/userpanel',
        '/customers', '/users', '/administration', '/sysadmin', '/system',
        '/rootadmin', '/root-admin', '/manager', '/webadmin', '/web-admin',
        '/superadmin', '/super-admin', '/adminp', '/administratorp', '/adminpage',
        '/admin-page', '/adminpages', '/admin-pages', '/admincenter', '/admin-center',
        '/admin_area', '/memberadmin', '/member-admin', '/administrator_area',
        '/administrator-area', '/adminconsole', '/admin-console', '/admincontrol',
        '/admin-control', '/adminhome', '/admin-home', '/adminuser', '/admin-user',
        '/adminlogin', '/admin-login', '/admin_auth', '/admin_authenticate',
        '/admin-auth', '/admin-authenticate', '/authadmin', '/authenticateadmin',
        '/auth_admin', '/authenticate_admin', '/authadministrator',
        '/authenticateadministrator', '/auth_administrator',
        '/authenticate_administrator', '/loginadmin', '/login-admin',
        '/loginadministrator', '/login-administrator', '/login_admin',
        '/login_administrator', '/loginpanel', '/login-panel', '/loginpage',
        '/login-page', '/adm1n', '/adm1nistrator', '/administr8r', '/adminn',
        '/administrador', '/adminstrator', '/adminstr8r', '/adminstr', '/adm1n1str',
        '/adminn1str', '/administrator1', '/admin1strator', '/admini',
        '/admiistrator', '/aministrator', '/superadmin1', '/adminlogin1',
        '/loginadmin1', '/login_admin1', '/loginadministrator1',
        '/login_administrator1', '/loginpanel1', '/loginpanel2', '/loginpanel3',
        '/loginpanel4', '/loginpanel5', '/loginpanel6', '/loginpanel7',
        '/loginpanel8', '/loginpanel9', '/loginpanel10', '/loginpanel11',
        '/loginpanel12', '/loginpanel13', '/loginpanel14', '/loginpanel15',
        '/adminv1', '/adminv2', '/adminv3', '/adminv4', '/adminv5', '/adminv6',
        '/adminv7', '/adminv8', '/adminv9', '/adminv10', '/adminv11', '/adminv12',
        '/adminv13', '/adminv14', '/adminv15', '/adminportal', '/admin-portal',
        '/superadmin', '/super-admin', '/controlpanel1', '/controlpanel2',
        '/controlpanel3', '/controlpanel4', '/controlpanel5', '/controlpanel6',
        '/controlpanel7', '/controlpanel8', '/controlpanel9', '/controlpanel10',
        '/controlpanel11', '/controlpanel12', '/controlpanel13', '/controlpanel14',
        '/controlpanel15', '/control_panel', '/control-panel', '/controlpanels',
        '/control-panels', '/administrator1', '/adminstrator1', '/administr8r1',
        '/adminn1str1', '/administrator2', '/adminstrator2', '/administr8r2',
        '/adminn1str2', '/administrator3', '/adminstrator3', '/administr8r3',
        '/adminn1str3', '/administrator4', '/adminstrator4', '/administr8r4',
        '/adminn1str4', '/administrator5', '/adminstrator5', '/administr8r5',
        '/adminn1str5', '/administrator6', '/adminstrator6', '/administr8r6',
        '/adminn1str6', '/administrator7', '/adminstrator7', '/administr8r7',
        '/adminn1str7', '/administrator8', '/adminstrator8', '/administr8r8',
        '/adminn1str8', '/administrator9', '/adminstrator9', '/administr8r9',
        '/adminn1str9', '/administrator10', '/adminstrator10', '/administr8r10',
        '/adminn1str10', '/administrateur', '/admi', '/admini', '/administrador',
        '/adminstrateur', '/adminin', '/administrat1on', '/administrat10n',
        '/administrat1o1', '/administrat10n1', '/admi1', '/admi1n', '/admi7',
        '/adm1', '/adm1n1strat0r', '/adm1n1strat0r1', '/adm1n1strat0r2',
        '/adm1n1strat0r3', '/adm1n1strat0r4', '/adm1n1strat0r5', '/adm1n1strat0r6',
        '/adm1n1strat0r7', '/adm1n1strat0r8', '/adm1n1strat0r9', '/adm1n1strat10r',
        '/adm1n1strat0r10', '/adm1nistrat0r', '/adm1nistrat0r1', '/adm1nistrat0r2',
        '/adm1nistrat0r3', '/adm1nistrat0r4', '/adm1nistrat0r5', '/adm1nistrat0r6',
        '/adm1nistrat0r7', '/adm1nistrat0r8', '/adm1nistrat0r9', '/adm1nistrat10r',
        '/adm1nistrat0r10', '/administrat0r', '/administrat0r1', '/administrat0r2',
        '/administrat0r3', '/administrat0r4', '/administrat0r5', '/administrat0r6',
        '/administrat0r7', '/administrat0r8', '/administrat0r9', '/administrat10r',
        '/administrat0r10', '/administratuer', '/administratuer1', '/administratuer2',
        '/administratuer3', '/administratuer4', '/administratuer5', '/administratuer6',
        '/administratuer7', '/administratuer8', '/administratuer9', '/administratuer10',
        '/administratuer11', '/administratuer12', '/administratuer13', '/administratuer14',
        '/administratuer15', '/administratuer16', '/administratuer17', '/administratuer18',
        '/administratuer19', '/administratuer20', '/administratuer21', '/administratuer22',
        '/administratuer23', '/administratuer24', '/administratuer25', '/administratuer26',
        '/administratuer27', '/administratuer28', '/administratuer29', '/administratuer30',
        '/administratuer31', '/administratuer32', '/administratuer33', '/administratuer34',
        '/administratuer35', '/administratuer36', '/administratuer37', '/administratuer38',
        '/administratuer39', '/administratuer40', '/administratuer41', '/administratuer42',
        '/administratuer43', '/administratuer44', '/administratuer45', '/administratuer46',
        '/administratuer47', '/administratuer48', '/administratuer49', '/administratuer50',
        '/administratuer51', '/administratuer52', '/administratuer53', '/administratuer54',
        '/administratuer55', '/administratuer56', '/administratuer57', '/administratuer58',
        '/administratuer59', '/administratuer60', '/administratuer61', '/administratuer62',
        '/administratuer63', '/administratuer64', '/administratuer65', '/administratuer66',
        '/administratuer67', '/administratuer68', '/administratuer69', '/administratuer70',
        '/administratuer71', '/administratuer72', '/administratuer73', '/administratuer74',
        '/administratuer75', '/administratuer76', '/administratuer77', '/administratuer78',
        '/administratuer79', '/administratuer80', '/administratuer81', '/administratuer82',
        '/administratuer83', '/administratuer84', '/administratuer85', '/administratuer86',
        '/administratuer87', '/administratuer88', '/administratuer89', '/administratuer90',
        '/administratuer91', '/administratuer92', '/administratuer93', '/administratuer94',
        '/administratuer95', '/administratuer96', '/administratuer97', '/administratuer98',
        '/administratuer99', '/administratuer100', '/super-administrator',
        '/super-administrator1', '/super-administrator2', '/super-administrator3',
        '/super-administrator4', '/super-administrator5', '/super-administrator6',
        '/super-administrator7', '/super-administrator8', '/super-administrator9',
        '/super-administrator10', '/super-administrator11', '/super-administrator12',
        '/super-administrator13', '/super-administrator14', '/super-administrator15',
        '/super-administrator16', '/super-administrator17', '/super-administrator18',
        '/super-administrator19', '/super-administrator20', '/super-administrator21',
        '/super-administrator22', '/super-administrator23', '/super-administrator24',
        '/super-administrator25', '/super-administrator26', '/super-administrator27',
        '/super-administrator28', '/super-administrator29', '/super-administrator30',
        '/super-administrator31', '/super-administrator32', '/super-administrator33',
        '/super-administrator34', '/super-administrator35', '/super-administrator36',
        '/super-administrator37', '/super-administrator38', '/super-administrator39',
        '/super-administrator40', '/super-administrator41', '/super-administrator42',
        '/super-administrator43', '/super-administrator44', '/super-administrator45',
        '/super-administrator46', '/super-administrator47', '/super-administrator48',
        '/super-administrator49', '/super-administrator50', '/super-administrator51',
        '/super-administrator52', '/super-administrator53', '/super-administrator54',
        '/super-administrator55', '/super-administrator56', '/super-administrator57',
        '/super-administrator58', '/super-administrator59', '/super-administrator60',
        '/super-administrator61', '/super-administrator62', '/super-administrator63',
        '/super-administrator64', '/super-administrator65', '/super-administrator66',
        '/super-administrator67', '/super-administrator68', '/super-administrator69',
        '/super-administrator70', '/super-administrator71', '/super-administrator72',
        '/super-administrator73', '/super-administrator74', '/super-administrator75',
        '/super-administrator76', '/super-administrator77', '/super-administrator78',
        '/super-administrator79', '/super-administrator80', '/super-administrator81',
        '/super-administrator82', '/super-administrator83', '/super-administrator84',
        '/super-administrator85', '/super-administrator86', '/super-administrator87',
        '/super-administrator88', '/super-administrator89', '/super-administrator90',
        '/super-administrator91', '/super-administrator92', '/super-administrator93',
        '/super-administrator94', '/super-administrator95', '/super-administrator96',
        '/super-administrator97', '/super-administrator98', '/super-administrator99',
        '/super-administrator100', '/god', '/power', '/wizard', '/megalogin',
        '/megalogin1', '/megalogin2', '/megalogin3', '/megalogin4', '/megalogin5',
        '/megalogin6', '/megalogin7', '/megalogin8', '/megalogin9', '/megalogin10',
        '/megalogin11', '/megalogin12', '/megalogin13', '/megalogin14', '/megalogin15',
        '/admin_login', '/administrator_login', '/admin-login', '/administrator-login',
        '/adminlogin', '/administratorlogin', '/adminpanel', '/administratorpanel',
        '/admin-panel', '/administrator-panel', '/adminhome', '/administratorhome',
        '/admin-home', '/administrator-home', '/admincenter', '/administratorcenter',
        '/admin-center', '/administrator-center', '/adminarea', '/administratorarea',
        '/admin-area', '/administrator-area', '/admincp', '/administratorcp',
        '/admin-cp', '/administrator-cp', '/admincontrol', '/administratorcontrol',
        '/admin-control', '/administrator-control', '/adminmanagement',
        '/administratormanagement', '/admin-management', '/administrator-management',
        '/adminconsole', '/administratorconsole', '/admin-console',
        '/administrator-console', '/adminaccess', '/administratoraccess',
        '/admin-access', '/administrator-access', '/adminsys', '/administratorsys',
        '/admin-sys', '/administrator-sys', '/admintools', '/administratortools',
        '/admin-tools', '/administrator-tools', '/adminutils', '/administratorutils',
        '/admin-utils', '/administrator-utils', '/adminpage', '/administratorpage',
        '/admin-page', '/administrator-page', '/adminpages', '/administratorpages',
        '/admin-pages', '/administrator-pages', '/adminportal', '/administratorportal',
        '/admin-portal', '/administrator-portal', '/superuser', '/rootuser',
        '/root-admin', '/rootadmin', '/super-admin', '/superadmin', '/godmode',
        '/masterlogin', '/master-login', '/mainadmin', '/main-admin', '/mainlogin',
        '/main-login', '/masteradmin', '/master-admin', '/masterpage', '/master-page',
        '/mastersys', '/master-sys', '/mastersystem', '/master-system', '/superlogin',
        '/super-login', '/superuserlogin', '/super-user-login', '/systemlogin',
        '/system-login', '/ultimateadmin', '/ultimate-admin', '/ultimateuser',
        '/ultimate-user', '/portaladmin', '/portal-admin', '/portaluser',
        '/portal-user', '/portalsys', '/portal-sys', '/portaladmin1', '/portaladmin2',
        '/portaladmin3', '/portaladmin4', '/portaladmin5', '/portaladmin6',
        '/portaladmin7', '/portaladmin8', '/portaladmin9', '/portaladmin10',
        '/portaladmin11', '/portaladmin12', '/portaladmin13', '/portaladmin14',
        '/portaladmin15', '/portaladmin16', '/portaladmin17', '/portaladmin18',
        '/portaladmin19', '/portaladmin20', '/portaladmin21', '/portaladmin22',
        '/portaladmin23', '/portaladmin24', '/portaladmin25', '/portaladmin26',
        '/portaladmin27', '/portaladmin28', '/portaladmin29', '/portaladmin30',
        '/portaladmin31', '/portaladmin32', '/portaladmin33', '/portaladmin34',
        '/portaladmin35', '/portaladmin36', '/portaladmin37', '/portaladmin38',
        '/portaladmin39', '/portaladmin40', '/portaladmin41', '/portaladmin42',
        '/portaladmin43', '/portaladmin44', '/portaladmin45', '/portaladmin46',
        '/portaladmin47', '/portaladmin48', '/portaladmin49', '/portaladmin50',
        '/portaladmin51', '/portaladmin52', '/portaladmin53', '/portaladmin54',
        '/portaladmin55', '/portaladmin56', '/portaladmin57', '/portaladmin58',
        '/portaladmin59', '/portaladmin60', '/portaladmin61', '/portaladmin62',
        '/portaladmin63', '/portaladmin64', '/portaladmin65', '/portaladmin66',
        '/portaladmin67', '/portaladmin68', '/portaladmin69', '/portaladmin70',
        '/portaladmin71', '/portaladmin72', '/portaladmin73', '/portaladmin74',
        '/portaladmin75', '/portaladmin76', '/portaladmin77', '/portaladmin78',
        '/portaladmin79', '/portaladmin80', '/portaladmin81', '/portaladmin82',
        '/portaladmin83', '/portaladmin84', '/portaladmin85', '/portaladmin86',
        '/portaladmin87', '/portaladmin88', '/portaladmin89', '/portaladmin90',
        '/portaladmin91', '/portaladmin92', '/portaladmin93', '/portaladmin94',
        '/portaladmin95', '/portaladmin96', '/portaladmin97', '/portaladmin98',
        '/portaladmin99', '/portaladmin100', '/portaladministrator', '/portal-administrator',
        '/portal-administrators', '/portaladministrators', '/portaladministrat0r',
        '/portaladministrat0r1', '/portaladministrat0r2', '/portaladministrat0r3',
        '/portaladministrat0r4', '/portaladministrat0r5', '/portaladministrat0r6',
        '/portaladministrat0r7', '/portaladministrat0r8', '/portaladministrat0r9',
        '/portaladministrat0r10', '/portaladministrateur', '/portaladministrateur1',
        '/portaladministrateur2', '/portaladministrateur3', '/portaladministrateur4',
        '/portaladministrateur5', '/portaladministrateur6', '/portaladministrateur7',
        '/portaladministrateur8', '/portaladministrateur9', '/portaladministrateur10',
        '/portaladminstrator', '/portaladminstrator1', '/portaladminstrator2',
        '/portaladminstrator3', '/portaladminstrator4', '/portaladminstrator5',
        '/portaladminstrator6', '/portaladminstrator7', '/portaladminstrator8',
        '/portaladminstrator9', '/portaladminstrator10', '/portaladmin1strator',
        '/portaladmin1strator1', '/portaladmin1strator2', '/portaladmin1strator3',
        '/portaladmin1strator4', '/portaladmin1strator5', '/portaladmin1strator6',
        '/portaladmin1strator7', '/portaladmin1strator8', '/portaladmin1strator9',
        '/portaladmin1strator10', '/portaladmin1strateur', '/portaladmin1strateur1',
        '/portaladmin1strateur2', '/portaladmin1strateur3', '/portaladmin1strateur4',
        '/portaladmin1strateur5', '/portaladmin1strateur6', '/portaladmin1strateur7',
        '/portaladmin1strateur8', '/portaladmin1strateur9', '/portaladmin1strateur10',
        '/portaladmin1strat0r', '/portaladmin1strat0r1', '/portaladmin1strat0r2',
        '/portaladmin1strat0r3', '/portaladmin1strat0r4', '/portaladmin1strat0r5',
        '/portaladmin1strat0r6', '/portaladmin1strat0r7', '/portaladmin1strat0r8',
        '/portaladmin1strat0r9', '/portaladmin1strat0r10', '/portaladmin1strator',
        '/portaladmin1strator1', '/portaladmin1strator2', '/portaladmin1strator3',
        '/portaladmin1strator4', '/portaladmin1strator5', '/portaladmin1strator6',
        '/portaladmin1strator7', '/portaladmin1strator8', '/portaladmin1strator9',
        '/portaladmin1strator10', '/portaladministrat0r', '/portaladministrat0r1',
        '/portaladministrat0r2', '/portaladministrat0r3', '/portaladministrat0r4',
        '/portaladministrat0r5', '/portaladministrat0r6', '/portaladministrat0r7',
        '/portaladministrat0r8', '/portaladministrat0r9',

    ]
    return common_admin_paths

if __name__ == "__main__":
    asyncio.run(main())
